name: CCoinCraft
version: '1.0-SNAPSHOT'
main: org.lch.cCoinCraft.CCoinCraft
api-version: '1.20'
commands:
  ccc:
    description: CCoinCraft main command
    usage: /ccc btc [buy/sell/balance] <amount>
    aliases: [ccc]