name: CCoinCraft
main: org.lch.cCoinCraft.CCoinCraft
version: 1.0
api-version: 1.13
commands:
  ccc:
    description: CCoinCraft commands
    usage: /<command> [buy/sell/balance/wallet/price/give/set/take]
    aliases: [ccc]
    permission: ccoincraft.use
    permission-message: You do not have permission to use this command.
permissions:
  ccoincraft.use:
    description: Allows use of CCoinCraft commands
    default: true
  ccoincraft.admin:
    description: Allows admin commands for CCoinCraft
    default: op